spring:
  application:
    name: kafka-idempotent-payment-consumer

  datasource:
    url: jdbc:postgresql://localhost:5441/payment_db
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: PaymentHikariPool

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-settlement-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    listener:
      ack-mode: MANUAL_IMMEDIATE

payment:
  kafka:
    topic: payment-settlements

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [corr-id=%X{correlation_id:-none}] %-5level %logger{36} - %msg%n"